.PHONY: help
help:
	echo "hi"

.PHONY: cleandata
cleandata:
	rm -f dataset.tar.gz
	rm -f weights/*
	rm -f dataset/testset/*
	rm -f dataset/trainset/*
	rm -f dataset/valset/*
	rm -f save_dir/e* save_dir/cost.npy